### ISSUE TITLE
Question About the simulation data

### ISSUE THREAD

**Issue by Gatsby23** [engcang/S-MSCKF-application#1]
Hi, Could please tell me where can dowload the airsim simulation environment and can we speed up the UAV's speed？

**Comment by engcang** [comment]
@Gatsby23 Hi. Did you read the README of this repo? I did not use airsim but I used FlightGoggles.
You can download and install it from [here](https://flightgoggles.mit.edu/).
Yeah, using the FlightGoggles simulator, you can freely control it.

**Comment by Gatsby23** [comment]
> @Gatsby23 Hi. Did you read the README of this repo? I did not use airsim but I used FlightGoggles.
> You can download and install it from [here](https://flightgoggles.mit.edu/).
> Yeah, using the FlightGoggles simulator, you can freely control it.

Thank you very much! I misunderstood the meaning of FlightGoggles, Sorry about that!
